# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sad_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1010, 843)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.homeTab = QtWidgets.QWidget()
        self.homeTab.setObjectName("homeTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.homeTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.homeTabWidget = QtWidgets.QTabWidget(self.homeTab)
        self.homeTabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.homeTabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.homeTabWidget.setIconSize(QtCore.QSize(150, 50))
        self.homeTabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.homeTabWidget.setDocumentMode(False)
        self.homeTabWidget.setTabsClosable(False)
        self.homeTabWidget.setObjectName("homeTabWidget")
        self.homeCpuTab = QtWidgets.QWidget()
        self.homeCpuTab.setObjectName("homeCpuTab")
        self.gridLayout = QtWidgets.QGridLayout(self.homeCpuTab)
        self.gridLayout.setObjectName("gridLayout")
        self.cpuSetupMonitorsGroupBox = QtWidgets.QGroupBox(self.homeCpuTab)
        self.cpuSetupMonitorsGroupBox.setFlat(False)
        self.cpuSetupMonitorsGroupBox.setCheckable(False)
        self.cpuSetupMonitorsGroupBox.setObjectName("cpuSetupMonitorsGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.cpuSetupMonitorsGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cpuProcessesGroupBox = QtWidgets.QGroupBox(self.cpuSetupMonitorsGroupBox)
        self.cpuProcessesGroupBox.setCheckable(True)
        self.cpuProcessesGroupBox.setObjectName("cpuProcessesGroupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.cpuProcessesGroupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.cpuProcessesTextEdit = QtWidgets.QTextEdit(self.cpuProcessesGroupBox)
        self.cpuProcessesTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.cpuProcessesTextEdit.setObjectName("cpuProcessesTextEdit")
        self.verticalLayout_6.addWidget(self.cpuProcessesTextEdit)
        self.verticalLayout.addWidget(self.cpuProcessesGroupBox)
        self.cpuTopProcessesCheckBox = QtWidgets.QCheckBox(self.cpuSetupMonitorsGroupBox)
        self.cpuTopProcessesCheckBox.setObjectName("cpuTopProcessesCheckBox")
        self.verticalLayout.addWidget(self.cpuTopProcessesCheckBox)
        self.cpuStartMonitorsPushButton = QtWidgets.QPushButton(self.cpuSetupMonitorsGroupBox)
        self.cpuStartMonitorsPushButton.setAutoDefault(False)
        self.cpuStartMonitorsPushButton.setDefault(False)
        self.cpuStartMonitorsPushButton.setObjectName("cpuStartMonitorsPushButton")
        self.verticalLayout.addWidget(self.cpuStartMonitorsPushButton)
        self.gridLayout.addWidget(self.cpuSetupMonitorsGroupBox, 0, 0, 1, 1)
        self.cpuRunningMonitorsGroupBox = QtWidgets.QGroupBox(self.homeCpuTab)
        self.cpuRunningMonitorsGroupBox.setObjectName("cpuRunningMonitorsGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.cpuRunningMonitorsGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cpuRunningMonitorsListWidget = QtWidgets.QListWidget(self.cpuRunningMonitorsGroupBox)
        self.cpuRunningMonitorsListWidget.setObjectName("cpuRunningMonitorsListWidget")
        item = QtWidgets.QListWidgetItem()
        self.cpuRunningMonitorsListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.cpuRunningMonitorsListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.cpuRunningMonitorsListWidget.addItem(item)
        self.verticalLayout_2.addWidget(self.cpuRunningMonitorsListWidget)
        self.cpuStopMonitorPushButton = QtWidgets.QPushButton(self.cpuRunningMonitorsGroupBox)
        self.cpuStopMonitorPushButton.setObjectName("cpuStopMonitorPushButton")
        self.verticalLayout_2.addWidget(self.cpuStopMonitorPushButton)
        self.gridLayout.addWidget(self.cpuRunningMonitorsGroupBox, 0, 1, 1, 1)
        self.homeTabWidget.addTab(self.homeCpuTab, "")
        self.homeErrorsTab = QtWidgets.QWidget()
        self.homeErrorsTab.setObjectName("homeErrorsTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.homeErrorsTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.errorsSetupMonitorsGroupBox = QtWidgets.QGroupBox(self.homeErrorsTab)
        self.errorsSetupMonitorsGroupBox.setFlat(False)
        self.errorsSetupMonitorsGroupBox.setCheckable(False)
        self.errorsSetupMonitorsGroupBox.setObjectName("errorsSetupMonitorsGroupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.errorsSetupMonitorsGroupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.errorsProcessesGroupBox = QtWidgets.QGroupBox(self.errorsSetupMonitorsGroupBox)
        self.errorsProcessesGroupBox.setCheckable(True)
        self.errorsProcessesGroupBox.setObjectName("errorsProcessesGroupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.errorsProcessesGroupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.errorsProcessesTextEdit = QtWidgets.QTextEdit(self.errorsProcessesGroupBox)
        self.errorsProcessesTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.errorsProcessesTextEdit.setObjectName("errorsProcessesTextEdit")
        self.verticalLayout_7.addWidget(self.errorsProcessesTextEdit)
        self.verticalLayout_5.addWidget(self.errorsProcessesGroupBox)
        self.errorsTopSystemCallsCheckBox = QtWidgets.QCheckBox(self.errorsSetupMonitorsGroupBox)
        self.errorsTopSystemCallsCheckBox.setObjectName("errorsTopSystemCallsCheckBox")
        self.verticalLayout_5.addWidget(self.errorsTopSystemCallsCheckBox)
        self.errorsSystemCallsTimeCheckBox = QtWidgets.QCheckBox(self.errorsSetupMonitorsGroupBox)
        self.errorsSystemCallsTimeCheckBox.setObjectName("errorsSystemCallsTimeCheckBox")
        self.verticalLayout_5.addWidget(self.errorsSystemCallsTimeCheckBox)
        self.errorsTopFilesCheckBox = QtWidgets.QCheckBox(self.errorsSetupMonitorsGroupBox)
        self.errorsTopFilesCheckBox.setObjectName("errorsTopFilesCheckBox")
        self.verticalLayout_5.addWidget(self.errorsTopFilesCheckBox)
        self.errorsTopProcessesCheckBox = QtWidgets.QCheckBox(self.errorsSetupMonitorsGroupBox)
        self.errorsTopProcessesCheckBox.setObjectName("errorsTopProcessesCheckBox")
        self.verticalLayout_5.addWidget(self.errorsTopProcessesCheckBox)
        self.errorsFileOpensCheckBox = QtWidgets.QCheckBox(self.errorsSetupMonitorsGroupBox)
        self.errorsFileOpensCheckBox.setObjectName("errorsFileOpensCheckBox")
        self.verticalLayout_5.addWidget(self.errorsFileOpensCheckBox)
        self.errorsFilesTimeCheckBox = QtWidgets.QCheckBox(self.errorsSetupMonitorsGroupBox)
        self.errorsFilesTimeCheckBox.setObjectName("errorsFilesTimeCheckBox")
        self.verticalLayout_5.addWidget(self.errorsFilesTimeCheckBox)
        self.errorsStartMonitorsPushButton = QtWidgets.QPushButton(self.errorsSetupMonitorsGroupBox)
        self.errorsStartMonitorsPushButton.setAutoDefault(False)
        self.errorsStartMonitorsPushButton.setDefault(False)
        self.errorsStartMonitorsPushButton.setObjectName("errorsStartMonitorsPushButton")
        self.verticalLayout_5.addWidget(self.errorsStartMonitorsPushButton)
        self.gridLayout_2.addWidget(self.errorsSetupMonitorsGroupBox, 0, 0, 1, 1)
        self.errorsRunningMonitorsGroupBox = QtWidgets.QGroupBox(self.homeErrorsTab)
        self.errorsRunningMonitorsGroupBox.setObjectName("errorsRunningMonitorsGroupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.errorsRunningMonitorsGroupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.errorsRunningMonitorsListWidget = QtWidgets.QListWidget(self.errorsRunningMonitorsGroupBox)
        self.errorsRunningMonitorsListWidget.setObjectName("errorsRunningMonitorsListWidget")
        item = QtWidgets.QListWidgetItem()
        self.errorsRunningMonitorsListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.errorsRunningMonitorsListWidget.addItem(item)
        self.verticalLayout_4.addWidget(self.errorsRunningMonitorsListWidget)
        self.errorsStopMonitorPushButton = QtWidgets.QPushButton(self.errorsRunningMonitorsGroupBox)
        self.errorsStopMonitorPushButton.setObjectName("errorsStopMonitorPushButton")
        self.verticalLayout_4.addWidget(self.errorsStopMonitorPushButton)
        self.gridLayout_2.addWidget(self.errorsRunningMonitorsGroupBox, 0, 1, 1, 1)
        self.homeTabWidget.addTab(self.homeErrorsTab, "")
        self.homeNetworkTab = QtWidgets.QWidget()
        self.homeNetworkTab.setObjectName("homeNetworkTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.homeNetworkTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.networkSetupMonitorsGroupBox = QtWidgets.QGroupBox(self.homeNetworkTab)
        self.networkSetupMonitorsGroupBox.setFlat(False)
        self.networkSetupMonitorsGroupBox.setCheckable(False)
        self.networkSetupMonitorsGroupBox.setObjectName("networkSetupMonitorsGroupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.networkSetupMonitorsGroupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.networkHostsGroupBox = QtWidgets.QGroupBox(self.networkSetupMonitorsGroupBox)
        self.networkHostsGroupBox.setCheckable(True)
        self.networkHostsGroupBox.setObjectName("networkHostsGroupBox")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.networkHostsGroupBox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.networkHostsTextEdit = QtWidgets.QTextEdit(self.networkHostsGroupBox)
        self.networkHostsTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.networkHostsTextEdit.setObjectName("networkHostsTextEdit")
        self.verticalLayout_9.addWidget(self.networkHostsTextEdit)
        self.verticalLayout_8.addWidget(self.networkHostsGroupBox)
        self.networkTopProcessesCheckBox = QtWidgets.QCheckBox(self.networkSetupMonitorsGroupBox)
        self.networkTopProcessesCheckBox.setObjectName("networkTopProcessesCheckBox")
        self.verticalLayout_8.addWidget(self.networkTopProcessesCheckBox)
        self.networkTopClientsCheckBox = QtWidgets.QCheckBox(self.networkSetupMonitorsGroupBox)
        self.networkTopClientsCheckBox.setObjectName("networkTopClientsCheckBox")
        self.verticalLayout_8.addWidget(self.networkTopClientsCheckBox)
        self.networkStartMonitorsPushButton = QtWidgets.QPushButton(self.networkSetupMonitorsGroupBox)
        self.networkStartMonitorsPushButton.setAutoDefault(False)
        self.networkStartMonitorsPushButton.setDefault(False)
        self.networkStartMonitorsPushButton.setObjectName("networkStartMonitorsPushButton")
        self.verticalLayout_8.addWidget(self.networkStartMonitorsPushButton)
        self.gridLayout_3.addWidget(self.networkSetupMonitorsGroupBox, 0, 0, 1, 1)
        self.networkRunningMonitorsGroupBox = QtWidgets.QGroupBox(self.homeNetworkTab)
        self.networkRunningMonitorsGroupBox.setObjectName("networkRunningMonitorsGroupBox")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.networkRunningMonitorsGroupBox)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.networkRunningMonitorsListWidget = QtWidgets.QListWidget(self.networkRunningMonitorsGroupBox)
        self.networkRunningMonitorsListWidget.setObjectName("networkRunningMonitorsListWidget")
        item = QtWidgets.QListWidgetItem()
        self.networkRunningMonitorsListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.networkRunningMonitorsListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.networkRunningMonitorsListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.networkRunningMonitorsListWidget.addItem(item)
        self.verticalLayout_10.addWidget(self.networkRunningMonitorsListWidget)
        self.networkStopMonitorPushButton = QtWidgets.QPushButton(self.networkRunningMonitorsGroupBox)
        self.networkStopMonitorPushButton.setObjectName("networkStopMonitorPushButton")
        self.verticalLayout_10.addWidget(self.networkStopMonitorPushButton)
        self.gridLayout_3.addWidget(self.networkRunningMonitorsGroupBox, 0, 1, 1, 1)
        self.homeTabWidget.addTab(self.homeNetworkTab, "")
        self.homeSecurityTab = QtWidgets.QWidget()
        self.homeSecurityTab.setObjectName("homeSecurityTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.homeSecurityTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.securitySetupMonitorsGroupBox = QtWidgets.QGroupBox(self.homeSecurityTab)
        self.securitySetupMonitorsGroupBox.setFlat(False)
        self.securitySetupMonitorsGroupBox.setCheckable(False)
        self.securitySetupMonitorsGroupBox.setObjectName("securitySetupMonitorsGroupBox")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.securitySetupMonitorsGroupBox)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.securityLoginShellsGroupBox = QtWidgets.QGroupBox(self.securitySetupMonitorsGroupBox)
        self.securityLoginShellsGroupBox.setCheckable(True)
        self.securityLoginShellsGroupBox.setObjectName("securityLoginShellsGroupBox")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.securityLoginShellsGroupBox)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.securityLoginShellsTextEdit = QtWidgets.QTextEdit(self.securityLoginShellsGroupBox)
        self.securityLoginShellsTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.securityLoginShellsTextEdit.setObjectName("securityLoginShellsTextEdit")
        self.verticalLayout_13.addWidget(self.securityLoginShellsTextEdit)
        self.verticalLayout_12.addWidget(self.securityLoginShellsGroupBox)
        self.securityUserDirectoriesGroupBox = QtWidgets.QGroupBox(self.securitySetupMonitorsGroupBox)
        self.securityUserDirectoriesGroupBox.setCheckable(True)
        self.securityUserDirectoriesGroupBox.setObjectName("securityUserDirectoriesGroupBox")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.securityUserDirectoriesGroupBox)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.securityUserDirectoriesTextEdit = QtWidgets.QTextEdit(self.securityUserDirectoriesGroupBox)
        self.securityUserDirectoriesTextEdit.setObjectName("securityUserDirectoriesTextEdit")
        self.verticalLayout_14.addWidget(self.securityUserDirectoriesTextEdit)
        self.verticalLayout_12.addWidget(self.securityUserDirectoriesGroupBox)
        self.securityFileOpensGroupBox = QtWidgets.QGroupBox(self.securitySetupMonitorsGroupBox)
        self.securityFileOpensGroupBox.setCheckable(True)
        self.securityFileOpensGroupBox.setObjectName("securityFileOpensGroupBox")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.securityFileOpensGroupBox)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.securityFileOpensTextEdit = QtWidgets.QTextEdit(self.securityFileOpensGroupBox)
        self.securityFileOpensTextEdit.setObjectName("securityFileOpensTextEdit")
        self.verticalLayout_15.addWidget(self.securityFileOpensTextEdit)
        self.verticalLayout_12.addWidget(self.securityFileOpensGroupBox)
        self.securityStartMonitorsPushButton = QtWidgets.QPushButton(self.securitySetupMonitorsGroupBox)
        self.securityStartMonitorsPushButton.setAutoDefault(False)
        self.securityStartMonitorsPushButton.setDefault(False)
        self.securityStartMonitorsPushButton.setObjectName("securityStartMonitorsPushButton")
        self.verticalLayout_12.addWidget(self.securityStartMonitorsPushButton)
        self.gridLayout_4.addWidget(self.securitySetupMonitorsGroupBox, 0, 0, 1, 1)
        self.securityRunningMonitorsGroupBox = QtWidgets.QGroupBox(self.homeSecurityTab)
        self.securityRunningMonitorsGroupBox.setObjectName("securityRunningMonitorsGroupBox")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.securityRunningMonitorsGroupBox)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.securityRunningMonitorsListWidget = QtWidgets.QListWidget(self.securityRunningMonitorsGroupBox)
        self.securityRunningMonitorsListWidget.setObjectName("securityRunningMonitorsListWidget")
        item = QtWidgets.QListWidgetItem()
        self.securityRunningMonitorsListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.securityRunningMonitorsListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.securityRunningMonitorsListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.securityRunningMonitorsListWidget.addItem(item)
        self.verticalLayout_11.addWidget(self.securityRunningMonitorsListWidget)
        self.securityStopMonitorPushButton = QtWidgets.QPushButton(self.securityRunningMonitorsGroupBox)
        self.securityStopMonitorPushButton.setObjectName("securityStopMonitorPushButton")
        self.verticalLayout_11.addWidget(self.securityStopMonitorPushButton)
        self.gridLayout_4.addWidget(self.securityRunningMonitorsGroupBox, 0, 1, 1, 1)
        self.homeTabWidget.addTab(self.homeSecurityTab, "")
        self.homeAppTab = QtWidgets.QWidget()
        self.homeAppTab.setObjectName("homeAppTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.homeAppTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.appSetupMonitorsGroupBox = QtWidgets.QGroupBox(self.homeAppTab)
        self.appSetupMonitorsGroupBox.setFlat(False)
        self.appSetupMonitorsGroupBox.setCheckable(False)
        self.appSetupMonitorsGroupBox.setObjectName("appSetupMonitorsGroupBox")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.appSetupMonitorsGroupBox)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.appHTTPGroupBox = QtWidgets.QGroupBox(self.appSetupMonitorsGroupBox)
        self.appHTTPGroupBox.setCheckable(True)
        self.appHTTPGroupBox.setObjectName("appHTTPGroupBox")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.appHTTPGroupBox)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.appHTTPTextEdit = QtWidgets.QTextEdit(self.appHTTPGroupBox)
        self.appHTTPTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.appHTTPTextEdit.setObjectName("appHTTPTextEdit")
        self.verticalLayout_18.addWidget(self.appHTTPTextEdit)
        self.verticalLayout_17.addWidget(self.appHTTPGroupBox)
        self.appSQLGroupBox = QtWidgets.QGroupBox(self.appSetupMonitorsGroupBox)
        self.appSQLGroupBox.setCheckable(True)
        self.appSQLGroupBox.setObjectName("appSQLGroupBox")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.appSQLGroupBox)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.appSQLTextEdit = QtWidgets.QTextEdit(self.appSQLGroupBox)
        self.appSQLTextEdit.setObjectName("appSQLTextEdit")
        self.verticalLayout_19.addWidget(self.appSQLTextEdit)
        self.verticalLayout_17.addWidget(self.appSQLGroupBox)
        self.appStartMonitorsPushButton = QtWidgets.QPushButton(self.appSetupMonitorsGroupBox)
        self.appStartMonitorsPushButton.setAutoDefault(False)
        self.appStartMonitorsPushButton.setDefault(False)
        self.appStartMonitorsPushButton.setObjectName("appStartMonitorsPushButton")
        self.verticalLayout_17.addWidget(self.appStartMonitorsPushButton)
        self.gridLayout_5.addWidget(self.appSetupMonitorsGroupBox, 0, 0, 1, 1)
        self.appRunningMonitorsGroupBox = QtWidgets.QGroupBox(self.homeAppTab)
        self.appRunningMonitorsGroupBox.setObjectName("appRunningMonitorsGroupBox")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.appRunningMonitorsGroupBox)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.appRunningMonitorsListWidget = QtWidgets.QListWidget(self.appRunningMonitorsGroupBox)
        self.appRunningMonitorsListWidget.setObjectName("appRunningMonitorsListWidget")
        item = QtWidgets.QListWidgetItem()
        self.appRunningMonitorsListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.appRunningMonitorsListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.appRunningMonitorsListWidget.addItem(item)
        self.verticalLayout_16.addWidget(self.appRunningMonitorsListWidget)
        self.appStopMonitorPushButton = QtWidgets.QPushButton(self.appRunningMonitorsGroupBox)
        self.appStopMonitorPushButton.setObjectName("appStopMonitorPushButton")
        self.verticalLayout_16.addWidget(self.appStopMonitorPushButton)
        self.gridLayout_5.addWidget(self.appRunningMonitorsGroupBox, 0, 1, 1, 1)
        self.homeTabWidget.addTab(self.homeAppTab, "")
        self.verticalLayout_3.addWidget(self.homeTabWidget)
        self.mainTabWidget.addTab(self.homeTab, "")
        self.alertsTab = QtWidgets.QWidget()
        self.alertsTab.setObjectName("alertsTab")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.alertsTab)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.alertsTabWidget = QtWidgets.QTabWidget(self.alertsTab)
        self.alertsTabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.alertsTabWidget.setObjectName("alertsTabWidget")
        self.alertsCreateTab = QtWidgets.QWidget()
        self.alertsCreateTab.setObjectName("alertsCreateTab")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.alertsCreateTab)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.alertsTriggerGroupBox = QtWidgets.QGroupBox(self.alertsCreateTab)
        self.alertsTriggerGroupBox.setObjectName("alertsTriggerGroupBox")
        self.formLayout_4 = QtWidgets.QFormLayout(self.alertsTriggerGroupBox)
        self.formLayout_4.setObjectName("formLayout_4")
        self.alertsChooseMonitorLabel = QtWidgets.QLabel(self.alertsTriggerGroupBox)
        self.alertsChooseMonitorLabel.setObjectName("alertsChooseMonitorLabel")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.alertsChooseMonitorLabel)
        self.alertsSetMetricsLabel = QtWidgets.QLabel(self.alertsTriggerGroupBox)
        self.alertsSetMetricsLabel.setObjectName("alertsSetMetricsLabel")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.alertsSetMetricsLabel)
        self.alertsSetMetricsTextEdit = QtWidgets.QTextEdit(self.alertsTriggerGroupBox)
        self.alertsSetMetricsTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.alertsSetMetricsTextEdit.setLineWrapMode(QtWidgets.QTextEdit.FixedPixelWidth)
        self.alertsSetMetricsTextEdit.setOverwriteMode(False)
        self.alertsSetMetricsTextEdit.setObjectName("alertsSetMetricsTextEdit")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.alertsSetMetricsTextEdit)
        self.alertsChooseMonitorComboBox = QtWidgets.QComboBox(self.alertsTriggerGroupBox)
        self.alertsChooseMonitorComboBox.setObjectName("alertsChooseMonitorComboBox")
        self.alertsChooseMonitorComboBox.addItem("")
        self.alertsChooseMonitorComboBox.addItem("")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.alertsChooseMonitorComboBox)
        self.alertsAlertNameLabel = QtWidgets.QLabel(self.alertsTriggerGroupBox)
        self.alertsAlertNameLabel.setObjectName("alertsAlertNameLabel")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.alertsAlertNameLabel)
        self.alertsAlertNameTextEdit = QtWidgets.QTextEdit(self.alertsTriggerGroupBox)
        self.alertsAlertNameTextEdit.setObjectName("alertsAlertNameTextEdit")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.alertsAlertNameTextEdit)
        self.verticalLayout_22.addWidget(self.alertsTriggerGroupBox)
        self.alertsNotifyGroupBox = QtWidgets.QGroupBox(self.alertsCreateTab)
        self.alertsNotifyGroupBox.setObjectName("alertsNotifyGroupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.alertsNotifyGroupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.alertsNotifyCheckBox = QtWidgets.QCheckBox(self.alertsNotifyGroupBox)
        self.alertsNotifyCheckBox.setObjectName("alertsNotifyCheckBox")
        self.gridLayout_6.addWidget(self.alertsNotifyCheckBox, 1, 0, 1, 1)
        self.alertsEmailGroupBox = QtWidgets.QGroupBox(self.alertsNotifyGroupBox)
        self.alertsEmailGroupBox.setCheckable(True)
        self.alertsEmailGroupBox.setObjectName("alertsEmailGroupBox")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.alertsEmailGroupBox)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.alertsEmailTextEdit = QtWidgets.QTextEdit(self.alertsEmailGroupBox)
        self.alertsEmailTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.alertsEmailTextEdit.setObjectName("alertsEmailTextEdit")
        self.verticalLayout_21.addWidget(self.alertsEmailTextEdit)
        self.gridLayout_6.addWidget(self.alertsEmailGroupBox, 0, 0, 1, 1)
        self.verticalLayout_22.addWidget(self.alertsNotifyGroupBox)
        self.alertsActionGroupBox = QtWidgets.QGroupBox(self.alertsCreateTab)
        self.alertsActionGroupBox.setObjectName("alertsActionGroupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.alertsActionGroupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.alertsCaptureGroupBox = QtWidgets.QGroupBox(self.alertsActionGroupBox)
        self.alertsCaptureGroupBox.setCheckable(True)
        self.alertsCaptureGroupBox.setObjectName("alertsCaptureGroupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.alertsCaptureGroupBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.alertsFileNameTextEdit = QtWidgets.QTextEdit(self.alertsCaptureGroupBox)
        self.alertsFileNameTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.alertsFileNameTextEdit.setObjectName("alertsFileNameTextEdit")
        self.gridLayout_8.addWidget(self.alertsFileNameTextEdit, 3, 1, 1, 1)
        self.alertsCaptureDurationSpinBox = QtWidgets.QSpinBox(self.alertsCaptureGroupBox)
        self.alertsCaptureDurationSpinBox.setObjectName("alertsCaptureDurationSpinBox")
        self.gridLayout_8.addWidget(self.alertsCaptureDurationSpinBox, 1, 1, 1, 1)
        self.alertsCaptureDurationLabel = QtWidgets.QLabel(self.alertsCaptureGroupBox)
        self.alertsCaptureDurationLabel.setObjectName("alertsCaptureDurationLabel")
        self.gridLayout_8.addWidget(self.alertsCaptureDurationLabel, 1, 0, 1, 1)
        self.alertsFileNameLabel = QtWidgets.QLabel(self.alertsCaptureGroupBox)
        self.alertsFileNameLabel.setObjectName("alertsFileNameLabel")
        self.gridLayout_8.addWidget(self.alertsFileNameLabel, 3, 0, 1, 1)
        self.gridLayout_7.addWidget(self.alertsCaptureGroupBox, 0, 0, 1, 1)
        self.verticalLayout_22.addWidget(self.alertsActionGroupBox)
        self.alertsAddAlertPushButton = QtWidgets.QPushButton(self.alertsCreateTab)
        self.alertsAddAlertPushButton.setObjectName("alertsAddAlertPushButton")
        self.verticalLayout_22.addWidget(self.alertsAddAlertPushButton)
        self.alertsTabWidget.addTab(self.alertsCreateTab, "")
        self.alertsListTab = QtWidgets.QWidget()
        self.alertsListTab.setObjectName("alertsListTab")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.alertsListTab)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.alertsListGroupBox = QtWidgets.QGroupBox(self.alertsListTab)
        self.alertsListGroupBox.setObjectName("alertsListGroupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.alertsListGroupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.alertsListListWidget = QtWidgets.QListWidget(self.alertsListGroupBox)
        self.alertsListListWidget.setObjectName("alertsListListWidget")
        item = QtWidgets.QListWidgetItem()
        self.alertsListListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.alertsListListWidget.addItem(item)
        self.gridLayout_9.addWidget(self.alertsListListWidget, 0, 0, 1, 1)
        self.verticalLayout_24.addWidget(self.alertsListGroupBox)
        self.alertsListDeleteAlert = QtWidgets.QPushButton(self.alertsListTab)
        self.alertsListDeleteAlert.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.alertsListDeleteAlert.setObjectName("alertsListDeleteAlert")
        self.verticalLayout_24.addWidget(self.alertsListDeleteAlert)
        self.alertsTabWidget.addTab(self.alertsListTab, "")
        self.verticalLayout_20.addWidget(self.alertsTabWidget)
        self.mainTabWidget.addTab(self.alertsTab, "")
        self.notificationsTab = QtWidgets.QWidget()
        self.notificationsTab.setObjectName("notificationsTab")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.notificationsTab)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.notificationsTableWidget = QtWidgets.QTableWidget(self.notificationsTab)
        self.notificationsTableWidget.setWordWrap(True)
        self.notificationsTableWidget.setCornerButtonEnabled(True)
        self.notificationsTableWidget.setRowCount(3)
        self.notificationsTableWidget.setObjectName("notificationsTableWidget")
        self.notificationsTableWidget.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.notificationsTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.notificationsTableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.notificationsTableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.notificationsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.notificationsTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.notificationsTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.notificationsTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.notificationsTableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.notificationsTableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.notificationsTableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.notificationsTableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.notificationsTableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.notificationsTableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.notificationsTableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.notificationsTableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.notificationsTableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.notificationsTableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.notificationsTableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.notificationsTableWidget.setItem(2, 3, item)
        self.notificationsTableWidget.horizontalHeader().setVisible(False)
        self.notificationsTableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.notificationsTableWidget.horizontalHeader().setDefaultSectionSize(220)
        self.notificationsTableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.notificationsTableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.notificationsTableWidget.horizontalHeader().setStretchLastSection(True)
        self.notificationsTableWidget.verticalHeader().setVisible(False)
        self.notificationsTableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout_10.addWidget(self.notificationsTableWidget, 0, 0, 1, 1)
        self.mainTabWidget.addTab(self.notificationsTab, "")
        self.anomaliesTab = QtWidgets.QWidget()
        self.anomaliesTab.setObjectName("anomaliesTab")
        self.mainTabWidget.addTab(self.anomaliesTab, "")
        self.horizontalLayout.addWidget(self.mainTabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.mainTabWidget.setCurrentIndex(0)
        self.homeTabWidget.setCurrentIndex(0)
        self.alertsTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SAD UI"))
        self.cpuSetupMonitorsGroupBox.setTitle(_translate("MainWindow", "Setup monitors"))
        self.cpuProcessesGroupBox.setTitle(_translate("MainWindow", "Specify process to observe stdout (\"all\" for all processes)"))
        self.cpuProcessesTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.cpuProcessesTextEdit.setPlaceholderText(_translate("MainWindow", "One process per line (eg. cat)"))
        self.cpuTopProcessesCheckBox.setText(_translate("MainWindow", "Observe top processes in terms of CPU usage"))
        self.cpuStartMonitorsPushButton.setText(_translate("MainWindow", "Start monitors"))
        self.cpuRunningMonitorsGroupBox.setTitle(_translate("MainWindow", "Running monitors"))
        __sortingEnabled = self.cpuRunningMonitorsListWidget.isSortingEnabled()
        self.cpuRunningMonitorsListWidget.setSortingEnabled(False)
        item = self.cpuRunningMonitorsListWidget.item(0)
        item.setText(_translate("MainWindow", "top_process"))
        item = self.cpuRunningMonitorsListWidget.item(1)
        item.setText(_translate("MainWindow", "process_all"))
        item = self.cpuRunningMonitorsListWidget.item(2)
        item.setText(_translate("MainWindow", "process_cat"))
        self.cpuRunningMonitorsListWidget.setSortingEnabled(__sortingEnabled)
        self.cpuStopMonitorPushButton.setText(_translate("MainWindow", "Stop monitor"))
        self.homeTabWidget.setTabText(self.homeTabWidget.indexOf(self.homeCpuTab), _translate("MainWindow", "CPU && Processes"))
        self.errorsSetupMonitorsGroupBox.setTitle(_translate("MainWindow", "Setup monitors"))
        self.errorsProcessesGroupBox.setTitle(_translate("MainWindow", "Specify process to observe files where most time is spent (\"all\" for all processes)"))
        self.errorsProcessesTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.errorsProcessesTextEdit.setPlaceholderText(_translate("MainWindow", "One process per line (eg. cat)"))
        self.errorsTopSystemCallsCheckBox.setText(_translate("MainWindow", "Observer top system calls returning errors"))
        self.errorsSystemCallsTimeCheckBox.setText(_translate("MainWindow", "Observe system calls where most time has been spent"))
        self.errorsTopFilesCheckBox.setText(_translate("MainWindow", "Observe top files with I/O errors"))
        self.errorsTopProcessesCheckBox.setText(_translate("MainWindow", "Observe top processes with I/O errors"))
        self.errorsFileOpensCheckBox.setText(_translate("MainWindow", "Observe failed file opens"))
        self.errorsFilesTimeCheckBox.setText(_translate("MainWindow", "Observe files where most time has been spent"))
        self.errorsStartMonitorsPushButton.setText(_translate("MainWindow", "Start monitors"))
        self.errorsRunningMonitorsGroupBox.setTitle(_translate("MainWindow", "Running monitors"))
        self.errorsRunningMonitorsListWidget.setSortingEnabled(True)
        __sortingEnabled = self.errorsRunningMonitorsListWidget.isSortingEnabled()
        self.errorsRunningMonitorsListWidget.setSortingEnabled(False)
        item = self.errorsRunningMonitorsListWidget.item(0)
        item.setText(_translate("MainWindow", "fail_file_open"))
        item = self.errorsRunningMonitorsListWidget.item(1)
        item.setText(_translate("MainWindow", "top_file_io"))
        self.errorsRunningMonitorsListWidget.setSortingEnabled(__sortingEnabled)
        self.errorsStopMonitorPushButton.setText(_translate("MainWindow", "Stop monitor"))
        self.homeTabWidget.setTabText(self.homeTabWidget.indexOf(self.homeErrorsTab), _translate("MainWindow", "Performance && Errors"))
        self.networkSetupMonitorsGroupBox.setTitle(_translate("MainWindow", "Setup monitors"))
        self.networkHostsGroupBox.setTitle(_translate("MainWindow", "Specify host IPs to observe network data exchanged"))
        self.networkHostsTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.networkHostsTextEdit.setPlaceholderText(_translate("MainWindow", "One host per line (eg. 192.168.0.1)"))
        self.networkTopProcessesCheckBox.setText(_translate("MainWindow", "Observe top processes in terms of bandwidth"))
        self.networkTopClientsCheckBox.setText(_translate("MainWindow", "Observer top client IPs in terms of established connections"))
        self.networkStartMonitorsPushButton.setText(_translate("MainWindow", "Start monitors"))
        self.networkRunningMonitorsGroupBox.setTitle(_translate("MainWindow", "Running monitors"))
        self.networkRunningMonitorsListWidget.setSortingEnabled(True)
        __sortingEnabled = self.networkRunningMonitorsListWidget.isSortingEnabled()
        self.networkRunningMonitorsListWidget.setSortingEnabled(False)
        item = self.networkRunningMonitorsListWidget.item(0)
        item.setText(_translate("MainWindow", "netdata_10.10.10.10"))
        item = self.networkRunningMonitorsListWidget.item(1)
        item.setText(_translate("MainWindow", "netdata_192.168.0.1"))
        item = self.networkRunningMonitorsListWidget.item(2)
        item.setText(_translate("MainWindow", "top_client_IP"))
        item = self.networkRunningMonitorsListWidget.item(3)
        item.setText(_translate("MainWindow", "top_proc_bw"))
        self.networkRunningMonitorsListWidget.setSortingEnabled(__sortingEnabled)
        self.networkStopMonitorPushButton.setText(_translate("MainWindow", "Stop monitor"))
        self.homeTabWidget.setTabText(self.homeTabWidget.indexOf(self.homeNetworkTab), _translate("MainWindow", "Network"))
        self.securitySetupMonitorsGroupBox.setTitle(_translate("MainWindow", "Setup monitors"))
        self.securityLoginShellsGroupBox.setTitle(_translate("MainWindow", "Show all the commands executed by the login shell with given ID"))
        self.securityLoginShellsTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.securityLoginShellsTextEdit.setPlaceholderText(_translate("MainWindow", "One ID per line (eg. 5459)"))
        self.securityUserDirectoriesGroupBox.setTitle(_translate("MainWindow", "Show the directories that a user visits"))
        self.securityUserDirectoriesTextEdit.setPlaceholderText(_translate("MainWindow", "One user per line (eg. root)"))
        self.securityFileOpensGroupBox.setTitle(_translate("MainWindow", "Show every file open that happens in a directory"))
        self.securityFileOpensTextEdit.setPlaceholderText(_translate("MainWindow", "One directory per line (eg. /etc)"))
        self.securityStartMonitorsPushButton.setText(_translate("MainWindow", "Start monitors"))
        self.securityRunningMonitorsGroupBox.setTitle(_translate("MainWindow", "Running monitors"))
        self.securityRunningMonitorsListWidget.setSortingEnabled(True)
        __sortingEnabled = self.securityRunningMonitorsListWidget.isSortingEnabled()
        self.securityRunningMonitorsListWidget.setSortingEnabled(False)
        item = self.securityRunningMonitorsListWidget.item(0)
        item.setText(_translate("MainWindow", "commands_4310"))
        item = self.securityRunningMonitorsListWidget.item(1)
        item.setText(_translate("MainWindow", "commands_5459"))
        item = self.securityRunningMonitorsListWidget.item(2)
        item.setText(_translate("MainWindow", "dir_root"))
        item = self.securityRunningMonitorsListWidget.item(3)
        item.setText(_translate("MainWindow", "file_open_/etc"))
        self.securityRunningMonitorsListWidget.setSortingEnabled(__sortingEnabled)
        self.securityStopMonitorPushButton.setText(_translate("MainWindow", "Stop monitor"))
        self.homeTabWidget.setTabText(self.homeTabWidget.indexOf(self.homeSecurityTab), _translate("MainWindow", "Security"))
        self.appSetupMonitorsGroupBox.setTitle(_translate("MainWindow", "Setup monitors"))
        self.appHTTPGroupBox.setTitle(_translate("MainWindow", "Show all HTTP requests of specified type by the machine"))
        self.appHTTPTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.appHTTPTextEdit.setPlaceholderText(_translate("MainWindow", "One type per line (eg. GET, POST)"))
        self.appSQLGroupBox.setTitle(_translate("MainWindow", "Show all SQL queries of specified type by the machine"))
        self.appSQLTextEdit.setPlaceholderText(_translate("MainWindow", "One type per line (eg. SELECT, UPDATE)"))
        self.appStartMonitorsPushButton.setText(_translate("MainWindow", "Start monitors"))
        self.appRunningMonitorsGroupBox.setTitle(_translate("MainWindow", "Running monitors"))
        self.appRunningMonitorsListWidget.setSortingEnabled(True)
        __sortingEnabled = self.appRunningMonitorsListWidget.isSortingEnabled()
        self.appRunningMonitorsListWidget.setSortingEnabled(False)
        item = self.appRunningMonitorsListWidget.item(0)
        item.setText(_translate("MainWindow", "query_SELECT"))
        item = self.appRunningMonitorsListWidget.item(1)
        item.setText(_translate("MainWindow", "request_GET"))
        item = self.appRunningMonitorsListWidget.item(2)
        item.setText(_translate("MainWindow", "request_POST"))
        self.appRunningMonitorsListWidget.setSortingEnabled(__sortingEnabled)
        self.appStopMonitorPushButton.setText(_translate("MainWindow", "Stop monitor"))
        self.homeTabWidget.setTabText(self.homeTabWidget.indexOf(self.homeAppTab), _translate("MainWindow", "Application"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.homeTab), _translate("MainWindow", "Home"))
        self.alertsTriggerGroupBox.setTitle(_translate("MainWindow", "Trigger"))
        self.alertsChooseMonitorLabel.setText(_translate("MainWindow", "Choose monitor"))
        self.alertsSetMetricsLabel.setText(_translate("MainWindow", "Set metrics"))
        self.alertsSetMetricsTextEdit.setPlaceholderText(_translate("MainWindow", "Need to figure out how to do this"))
        self.alertsChooseMonitorComboBox.setItemText(0, _translate("MainWindow", "monitor_z"))
        self.alertsChooseMonitorComboBox.setItemText(1, _translate("MainWindow", "monitor_b"))
        self.alertsAlertNameLabel.setText(_translate("MainWindow", "Alert name"))
        self.alertsAlertNameTextEdit.setPlaceholderText(_translate("MainWindow", "Alert name(eg. alert_x)"))
        self.alertsNotifyGroupBox.setTitle(_translate("MainWindow", "Notify"))
        self.alertsNotifyCheckBox.setText(_translate("MainWindow", "Display alert to notifications tab"))
        self.alertsEmailGroupBox.setTitle(_translate("MainWindow", "Send alert to email"))
        self.alertsEmailTextEdit.setPlaceholderText(_translate("MainWindow", "email@email.com"))
        self.alertsActionGroupBox.setTitle(_translate("MainWindow", "Action"))
        self.alertsCaptureGroupBox.setTitle(_translate("MainWindow", "Set up capture"))
        self.alertsFileNameTextEdit.setPlaceholderText(_translate("MainWindow", "Meaningful filename"))
        self.alertsCaptureDurationLabel.setText(_translate("MainWindow", "Capture for (seconds)"))
        self.alertsFileNameLabel.setText(_translate("MainWindow", "Filename"))
        self.alertsAddAlertPushButton.setText(_translate("MainWindow", "Add alert"))
        self.alertsTabWidget.setTabText(self.alertsTabWidget.indexOf(self.alertsCreateTab), _translate("MainWindow", "Create"))
        self.alertsListGroupBox.setTitle(_translate("MainWindow", "Alert list"))
        self.alertsListListWidget.setSortingEnabled(True)
        __sortingEnabled = self.alertsListListWidget.isSortingEnabled()
        self.alertsListListWidget.setSortingEnabled(False)
        item = self.alertsListListWidget.item(0)
        item.setText(_translate("MainWindow", "alert_x"))
        item = self.alertsListListWidget.item(1)
        item.setText(_translate("MainWindow", "alert_y"))
        self.alertsListListWidget.setSortingEnabled(__sortingEnabled)
        self.alertsListDeleteAlert.setText(_translate("MainWindow", "Delete alert"))
        self.alertsTabWidget.setTabText(self.alertsTabWidget.indexOf(self.alertsListTab), _translate("MainWindow", "   List   "))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.alertsTab), _translate("MainWindow", "Alerts"))
        item = self.notificationsTableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.notificationsTableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.notificationsTableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.notificationsTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Datetime"))
        item = self.notificationsTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.notificationsTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Metric"))
        item = self.notificationsTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "File"))
        __sortingEnabled = self.notificationsTableWidget.isSortingEnabled()
        self.notificationsTableWidget.setSortingEnabled(False)
        item = self.notificationsTableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "2019-10-10 22:12:12"))
        item = self.notificationsTableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "alert_x"))
        item = self.notificationsTableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "metric_b"))
        item = self.notificationsTableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "captureX"))
        item = self.notificationsTableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "2019-10-11 22:12:12"))
        item = self.notificationsTableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "alert_x"))
        item = self.notificationsTableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "metric_z"))
        item = self.notificationsTableWidget.item(1, 3)
        item.setText(_translate("MainWindow", "-"))
        item = self.notificationsTableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "2019-10-9 22:12:12"))
        item = self.notificationsTableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "alert_y"))
        item = self.notificationsTableWidget.item(2, 2)
        item.setText(_translate("MainWindow", "metric_x"))
        item = self.notificationsTableWidget.item(2, 3)
        item.setText(_translate("MainWindow", "captureY"))
        self.notificationsTableWidget.setSortingEnabled(__sortingEnabled)
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.notificationsTab), _translate("MainWindow", "Notifications"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.anomaliesTab), _translate("MainWindow", "Anomalies"))

