#!/bin/bash

# update packages
sudo apt-get update -y
sudo apt-get upgrade -y

# setting up pip3
sudo apt-get install python3-pip
sudo -H pip3 install --upgrade pip

# install smad dependencies
pip3 install -r python_requirements.txt